# Generated by Django 4.0.3 on 2022-03-27 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessories'),
        ),
    ]
